# This workflow will generate the docs on each push, and publish them on GitHub Pages if the branch is the main one.
name: docs

on: [push]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create virtual environment
        run: uv venv

      - name: Install Python dependencies
        run: uv pip install -e ".[docs]"

      - name: Build Sphinx documentation
        run: uv run sphinx-build -a -E -b html docs build

      - name: Deploy Sphinx documentation on Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          BRANCH: gh-pages
          FOLDER: build/
