name: release-main

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Create virtual environment
        run: uv venv

      - name: Install build tools
        run: |
          uv pip install build twine

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/v} >> $GITHUB_OUTPUT

      - name: Set version from tag
        run: |
          uv pip install bump-my-version
          uv run bump-my-version set-version "${{ steps.vars.outputs.tag }}" --no-commit --no-tag

      - name: Build
        run: uv run python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: uv run twine upload dist/*
